services:
  nox:
    build: .
    depends_on:
      - elasticsearch
    ports:
      - "50051:50051"
      - "9090:9090"
    volumes:
      - ./detections:/detections
      - ./testdata:/app/testdata
      - ./intel:/intel
    environment:
      - NOX_RULES_PATH=/detections/rules.yaml
      - NOX_INTEL_PATH=/intel/ip_watchlist.txt
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
volumes:
  esdata: